### ISSUE TITLE
Can't dismount and glitching through the word

### ISSUE THREAD

**Issue by TheRealDadbeard** [m1k3s/parachute#10]
Using the newest available version and Forge2099|MC1.10.2 the mod works, but when flying my horizont flickers and i can't dismount and am clipping through the whole map.

EDIT:

Compiled it successfully now auto dismount and dismount per se works. But if you stay on the cute you will glitch through the map and die from suffocation. Seems to be a little glitchy too with realistic first person mod. Apart from that everything now works.

I'll just keep auto-dismount on so i will be fine till there be a new release .. hopefully :D

**Comment by m1k3s** [comment]
There is not any collision detection for the rider of the parachute, boat, horse, etc. Forge made a change to the dismount code, so you need to use a later version of forge for it to work properly. I think it was around version 2076.

**Comment by TheRealDadbeard** [comment]
Look into my comment. It says which version I'm using.

After compiling your latest source from here it works. Using the version thats on Curse is broken that i can't even dismount. I just stay on the parachute until i logout! :)

**Comment by m1k3s** [comment]
Sorry, I didn't see the version. I will update the Curse version.

**Comment by TheRealDadbeard** [comment]
Nice to hear! Yeah that one doesn't work good. Only issue that i sometimes had with the newest source here is that the horizont flashes, but only sometimes. Mostly when my player glitches kinda.. Dismounting and Auto-Dismount works good enough, just don't dismount yourself before hitting the ground with Auto-Dismount. Seems to freeze me too.

But in this state it's pretty usable. :)

**Comment by m1k3s** [comment]
The flickering started with Minecraft 1.10. It just happens to me as the sun is setting. I can't seem to get rid of it.

**Comment by TheRealDadbeard** [comment]
This excactly. Nothing major.
