### ISSUE TITLE
Flying in multiplayer and using thermal lift rises other players up too

### ISSUE THREAD

**Issue by TheRealDadbeard** [m1k3s/parachute#11]
So now i had the time to test this in MP and this excact issue happens. Was wondering why my son could descent and then i saw it myself :D

Another thing. Dismounting still is glitchy and often you are just stuck in the air. It's an amazing mod and looks really nice flying together :D

**Comment by m1k3s** [comment]
I had the issue with players on parachutes rising simultaneously resolved several versions back. The simple network wrapper should not be sending messages to all players. I'll have to check into that. I don't currently have a way to test multiplayer with more than just me on the server. This is the first time I've had anyone mention this issue in a long time.

**Comment by TheRealDadbeard** [comment]
Yeah everything was okay but then i and him started randomly rising and i did't know what was going on. After asking him to rise up i saw that i am too going up.

**Comment by m1k3s** [comment]
I have fixed (hopefully) the dismount bug on multiplayer. Maybe the issue with the server sending the ascend keypress to all instances of the parachute mod. I don't have a way to test with other players on multiplayer. I uploaded a new version (413) to curseforge. Give it a try and let me know.

**Comment by TheRealDadbeard** [comment]
Okay i will do that certainly tommorow!

**Comment by m1k3s** [comment]
Okay so the dismounting is now handled by minecraft. I was trying to use custom dismount code so that the player didn't act like they were dismounting from a boat, pig etc, off to the side. The skydiver should just dismount straight below the parachute. I will try to rework the custom code to work on the server, but at least it seems to work now.

Now on to the ascend keypress being active on all parachutes...

**Comment by m1k3s** [comment]
I just uploaded a new version of the 413 parachute mod to curseforge. I think I have the multiplayer ascend key bug fixed. When you can please try it and let me know. The new file should be approved soon. And thanks for helping me troubleshoot this bug.

**Comment by TheRealDadbeard** [comment]
Both player still ascent. Testing on two seperate machines so that is not an issue. Dismounting is still working fine.

**Comment by m1k3s** [comment]
I assume you have two separate accounts. I am using the player name to differentiate between clients. I'll keep working on this.

**Comment by TheRealDadbeard** [comment]
Yes everything is seperate.

**Comment by m1k3s** [comment]
okay, so once again I may have fixed this multiplayer control bug. I uploaded another version (414) to curseforge. Please give this a try and let me know. Thanks.

**Comment by TheRealDadbeard** [comment]
Works now! Thank you :D

**Comment by m1k3s** [comment]
Wow! Great! And to think I pulled the player management code back in 1.7.2 when I switched to using the SimpleNetworkWrapper. That was supposed to handle the per user stuff. Oh well. Glad it's fixed.And thanks for testing it!

**Comment by TheRealDadbeard** [comment]
Thank you for taking time out of your day for fixing this bug!

**Comment by m1k3s** [comment]
You're welcome. I'm still working on getting multiplayer bug free. Auto dismount seems to have an issue. It never ends...

**Comment by m1k3s** [comment]
FYI, I uploaded a new version to curseforge (415) that disables auto-dismount on multiplayer. I'll work to get it fixed eventually. This version should work better all around.
