### ISSUE TITLE
Configurable ascend not respected in branch 1.8.0

### ISSUE THREAD

**Issue by plnx** [m1k3s/parachute#2]
Looks like a `Keyboard.KEY_SPACE` was missed in [956197](https://github.com/m1k3s/parachute/commit/956197#diff-33e7bf7adf7c4d2cd9102156684b0e06R35)

Funny (as in, looks like something I would do), branch parachute-ng [caught it](https://github.com/m1k3s/parachute/commit/82035b6adf68b888dcfd22f08d704dd1e85d8cac#diff-33e7bf7adf7c4d2cd9102156684b0e06L34)

**Comment by m1k3s** [comment]
I fixed that, thanks! I posted the bug fixed parachute mod to CurseForge.
