### ISSUE TITLE
[enhancement] prevent user from going underground with shoot deployed

### ISSUE THREAD

**Issue by DanTheColoradan** [m1k3s/parachute#4]
I imagine you've thought of this, but would it be possible to have the user model stay approve ground while the shoot is deployed?

![2015-03-06_14 05 04](https://cloud.githubusercontent.com/assets/3826143/6536322/e1d9507c-c409-11e4-8701-ccd2facae5e6.png)

**Comment by m1k3s** [comment]
It's quite a problem. There are two things that help this to happen. First, it seems that the server doesn't keep up with the client regarding the player position. If you stay on the parachute for a minute or two and press LSHIFT to dismount while high enough to re-deploy you may find yourself falling in a different location from where you pressed LSHIFT. Also minecraft doesn't implement collision detection for the player riding the parachute, or boat or minecart either. So trying to keep the player above ground doesn't work reliably. Not only that, the auto dismount code checks the players altitude every iteration of the update function (about 20 times per second) and if the player is within 1 meter (block) of the ground, dismounts. So theoretically the player should not be able to go below ground as in your picture. So much for theory. I am still trying to figure out if there is anything I can reasonably do to fix this. The parachute mod should not have to re-implement the player, it should just be a parachute. Like the boat or minecart.

**Comment by DanTheColoradan** [comment]
Thanks for the info! I figured there was some reason it wasn't easy to / already implemented.
